export const getStateId = (stateName) =>
  ({
    Acre: 1,
    Alagoas: 2,
    Amapá: 3,
    Amazonas: 4,
    Bahia: 5,
    Ceará: 6,
    "Espírito Santo": 7,
    Goiás: 8,
    Maranhão: 9,
    "Mato Grosso": 10,
    "Mato Grosso do Sul": 11,
    "Minas Gerais": 12,
    Pará: 13,
    Paraná: 14,
    Paraíba: 15,
    Pernambuco: 16,
    Piauí: 17,
    "Rio de Janeiro": 18,
    "Rio Grande do Norte": 19,
    "Rio Grande do Sul": 20,
    Rondônia: 21,
    Roraima: 22,
    "Santa Catarina": 23,
    "São Paulo": 24,
    Sergipe: 25,
    Tocantins: 26,
    "Distrito Federal": 27,
  }[stateName]);
